name: ComposableTodo

# オプション設定
options:
  # バンドルプレフィックス
  bundleIdPrefix: algoria
  # LocalizationsのDevelopment Languageを指定
  developmentLanguage: ja

# Swift Package Managerのパッケージ設定
packages:
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture.git
    from: 1.19.0
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: 11.11.0

# ターゲットごとの設定
targets:
  ComposableTodo:
    # ターゲットの製品タイプ
    type: application
    # ターゲットのプラットフォーム
    platform: iOS
    # デプロイメントターゲット
    deploymentTarget: "17.0.0"

    # 採用するFirebaseのサービス
    dependencies:
      - package: Firebase
        product: FirebaseAnalytics
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseCore
      - package: Firebase
        product: FirebaseFirestore
      - package: ComposableArchitecture
        product: ComposableArchitecture

    # ソースコードとその他のファイル
    sources:
      - ComposableTodo
      - .gitignore
      - project.yml
    resources:
      - Resources

    # Run Script設定
    postCompileScripts:
      - path: ./Scripts/swiftLint.sh
        name: SwiftLint and SwiftFormat

    # ビルド設定
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: algoria.ComposableTodo
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        DEVELOPMENT_TEAM: ALGORIA
        OTHER_LDFLAGS:
          - $(inherited)
          - -ObjC
          - -all_load

    # Info.plist設定
    info:
      path: ComposableTodo/Info.plist
      properties:
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        LSRequiresIPhoneOS: YES
        UILaunchScreen: ""
        UIApplicationSupportsIndirectInputEvents: YES
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: YES
        UISupportedInterfaceOrientations~iphone:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIUserInterfaceStyle: Light

  ComposableTodoTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - ComposableTodoTests
    dependencies:
      - target: ComposableTodo
